title: Microservicio de acceso
description: Documentación del microservicio que gestiona la lógica de accesos y QRs de "SocioUnido"
theme: just-the-docs

url: "https://trabajoprofesional-aggz.github.io"

baseurl: "/microservicio-acceso"
